# Generated by Django 4.1.7 on 2023-10-07 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('Región de Arica y Parinacota', 'Región de Arica y Parinacota'), ('Región de Tarapacá', 'Región de Tarapacá'), ('Región de Antofagasta', 'Región de Antofagasta'), ('Región de Atacama', 'Región de Atacama'), ('Región de Coquimbo', 'Región de Coquimbo'), ('Región de Valparaíso', 'Región de Valparaíso'), ('Región Metropolitana', 'Región Metropolitana'), ("Región de Libertador General Bernardo O'Higgins", "Región de Libertador General Bernardo O'Higgins"), ('Región del Maule', 'Región del Maule'), ('Región del Biobio', 'Región del Biobio'), ('Región de la Araucanía', 'Región de la Araucanía'), ('Región de Los Ríos', 'Región de los Ríos'), ('Región de Los Lagos', 'Región de Los Lagos'), ('Región de Aysén', 'Región de Aysén'), ('Región de Magallanes', 'Región de Magallanes')], max_length=100, null=True, verbose_name='Región')),
                ('locality', models.CharField(max_length=200, verbose_name='Comuna')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('mobile', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='category')),
                ('subcategory_image', models.ImageField(upload_to='subcategory')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.IntegerField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('product_image', models.ImageField(upload_to='product')),
                ('stock', models.IntegerField(default=0)),
                ('item', models.BooleanField(default=False, help_text='0=default, 1=item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_option', models.CharField(choices=[('retiro', 'Pickup'), ('despacho', 'Delivery')], max_length=50)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Cotización enviada', 'Cotización enviada'), ('Cotización pendiente', 'Cotización pendiente')], default='Correo pendiente', max_length=50)),
                ('address', models.CharField(default='Store Pickup', max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='order_pdfs/')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('locality', models.CharField(max_length=200, verbose_name='Comuna')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('mobile', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('zipcode', models.IntegerField(verbose_name='Código postal')),
                ('state', models.CharField(choices=[('Región de Arica y Parinacota', 'Región de Arica y Parinacota'), ('Región de Tarapacá', 'Región de Tarapacá'), ('Región de Antofagasta', 'Región de Antofagasta'), ('Región de Atacama', 'Región de Atacama'), ('Región de Coquimbo', 'Región de Coquimbo'), ('Región de Valparaíso', 'Región de Valparaíso'), ('Región Metropolitana', 'Región Metropolitana'), ("Región de Libertador General Bernardo O'Higgins", "Región de Libertador General Bernardo O'Higgins"), ('Región del Maule', 'Región del Maule'), ('Región del Biobio', 'Región del Biobio'), ('Región de la Araucanía', 'Región de la Araucanía'), ('Región de Los Ríos', 'Región de los Ríos'), ('Región de Los Lagos', 'Región de Los Lagos'), ('Región de Aysén', 'Región de Aysén'), ('Región de Magallanes', 'Región de Magallanes')], max_length=100, verbose_name='Región')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
