# Generated by Django 4.2.1 on 2023-05-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('locality', models.CharField(max_length=200, verbose_name='Comuna')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('mobile', models.IntegerField(default=0, verbose_name='Teléfono')),
                ('zipcode', models.IntegerField(verbose_name='Código postal')),
                ('state', models.CharField(choices=[('Región de Arica y Parinacota', 'Región de Arica y Parinacota'), ('Región de Tarapacá', 'Región de Tarapacá'), ('Región de Antofagasta', 'Región de Antofagasta'), ('Región de Atacama', 'Región de Atacama'), ('Región de Coquimbo', 'Región de Coquimbo'), ('Región de Valparaíso', 'Región de Valparaíso'), ('Región Metropolitana', 'Región Metropolitana'), ("Región de Libertador General Bernardo O'Higgins", "Región de Libertador General Bernardo O'Higgins"), ('Región del Maule', 'Región del Maule'), ('Región del Biobio', 'Región del Biobio'), ('Región de la Araucanía', 'Región de la Araucanía'), ('Región de Los Ríos', 'Región de los Ríos'), ('Región de Los Lagos', 'Región de Los Lagos'), ('Región de Aysén', 'Región de Aysén'), ('Región de Magallanes', 'Región de Magallanes')], max_length=100, verbose_name='Región')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
