# Generated by Django 4.2.1 on 2023-05-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_product_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.IntegerField(),
        ),
    ]
