# Generated by Django 4.0.6 on 2023-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='webpay_order_id',
            new_name='mercadopago_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='webpay_payment_id',
            new_name='mercadopago_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='webpay_payment_status',
            new_name='mercadopago_payment_status',
        ),
    ]
