# Generated by Django 4.1.7 on 2023-10-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_information_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
