# Generated by Django 4.0.6 on 2023-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_selling_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price_currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(),
        ),
    ]
