# Generated by Django 4.1.7 on 2023-10-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_irrigat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='irrigat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.irrigat'),
        ),
    ]
