# Generated by Django 4.1.7 on 2023-06-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_title_product_name_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=0, upload_to='category'),
            preserve_default=False,
        ),
    ]
