# Generated by Django 4.1.7 on 2023-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_irrigat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='irrigat',
        ),
        migrations.DeleteModel(
            name='Irrigat',
        ),
    ]
