# Generated by Django 4.1.7 on 2023-10-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_irrigat_delete_irrigat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
