# Generated by Django 4.1.7 on 2023-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_image',
            field=models.ImageField(default=0, upload_to='subcategory'),
            preserve_default=False,
        ),
    ]
