# Generated by Django 4.1.7 on 2023-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_irrigat'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigat',
            name='composition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='item',
            field=models.BooleanField(default=False, help_text='0=default, 1=item'),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='prodapp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigat',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
