# Generated by Django 4.1.7 on 2023-10-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_irrigat_composition_irrigat_description_irrigat_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Irrigat',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='name',
            new_name='email',
        ),
    ]
