# Generated by Django 4.1.7 on 2023-10-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_information_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='quantity',
        ),
    ]
