# Generated by Django 4.1.7 on 2023-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cotización enviada', 'Cotización enviada'), ('Cotización pendiente', 'Cotización pendiente')], default='Pendiente', max_length=50),
        ),
    ]
