# Generated by Django 4.1.7 on 2023-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_information_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
