# Generated by Django 4.1.7 on 2023-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_information_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
