# Generated by Django 4.1.7 on 2023-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_information_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
