# Generated by Django 4.1.7 on 2023-09-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
