# Generated by Django 4.1.7 on 2023-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_category_category_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
