# Generated by Django 4.1.7 on 2023-09-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Store Pickup', max_length=200),
        ),
    ]
