# Generated by Django 4.1.7 on 2023-09-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
