# Generated by Django 4.1.7 on 2023-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order_status_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_changed',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('retiro', 'Pickup'), ('despacho', 'Delivery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cotización enviada', 'Cotización enviada'), ('Cotización pendiente', 'Cotización pendiente')], default='Correo pendiente', max_length=50),
        ),
    ]
