# Generated by Django 4.1.7 on 2023-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_order_status_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='order_pdfs/'),
        ),
    ]
