# Generated by Django 4.1.7 on 2023-09-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
