# Generated by Django 4.2.5 on 2023-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_remove_payment_user_delete_orderplaced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
